import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Axis Flare Enterprise",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  }
};

import { Toaster } from "sonner";
import { StoreProvider } from "@/lib/redux/provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body
        className="font-inter antialiased bg-background text-foreground"
      >
        <StoreProvider>
          {children}
        </StoreProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
